export enum Config {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',
  JWT_SECRET = 'JWT_SECRET',
  ACCESS_TOKEN_TTL = 'ACCESS_TOKEN_TTL',
  REFRESH_TOKEN_TTL = 'REFRESH_TOKEN_TTL',
  BASE_URL = 'BASE_URL',
  MAIL_HOST = 'MAIL_HOST',
  MAIL_USER = 'MAIL_USER',
  MAIL_PASS = 'MAIL_PASS',
}
